// Generated by CoffeeScript 1.4.0

/**
 * @package   Cherrytea common
 * @category  plugins
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  cs.cherrytea = cs.cherrytea || {};

  cs.cherrytea.popup = function() {
    return $.cs.simple_modal("<cherrytea-popup></cherrytea-popup>", true, 470);
  };

}).call(this);
