// Generated by CoffeeScript 1.4.0

/**
 * @package   Landing
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  Polymer({
    ready: function() {
      return $(function() {
        return $(this.querySelector('.cherrytea-landing-form form')).submit(function() {
          cs.form.send(this);
          return false;
        });
      });
    }
  });

}).call(this);
