// Generated by CoffeeScript 1.4.0

/**
 * @package   Form
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  cs.form = {
    send: function(form) {
      var data;
      data = {};
      $(form).serializeArray().forEach(function(item) {
        return data[item.name] = item.value;
      });
      return $.ajax({
        url: 'api/Form',
        data: data,
        type: 'post',
        success: function() {
          cs.cherrytea.popup();
          return $(form).each(function() {
            return this.reset();
          });
        }
      });
    }
  };

}).call(this);
