// Generated by CoffeeScript 1.4.0

/**
 * @package   Blogs
 * @category  modules
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  Polymer({
    ready: function() {
      var $short_content, date;
      this.post.comments_enabled = this.comments_enabled;
      this.post.read_more_text = cs.Language.read_more;
      $short_content = $(this.$.short_content);
      $short_content.html(this.post.short_content.replace(/<img([^>])+>/i, ''));
      (function(first_child) {
        if (first_child.is(':empty')) {
          return first_child.remove();
        }
      })($short_content.children().first());
      date = new Date(this.post.date * 1000);
      return this.date = ('0' + date.getDate()).slice(-2) + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + date.getFullYear();
    }
  });

}).call(this);
