// Generated by CoffeeScript 1.4.0

/**
 * @package   CherryTea.org
 * @category  themes
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  $(function() {
    return $(this.querySelector('.cherrytea-i-want-to-give-things-side-block form')).submit(function() {
      return cs.cherrytea.popup();
    });
  });

}).call(this);
