// Generated by CoffeeScript 1.4.0

/**
 * @package   Blogs cherrytea
 * @category  plugins
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  (function(L) {
    return Polymer({
      ready: function() {
        var date,
          _this = this;
        this["super"]();
        date = new Date(this.jsonld.date * 1000);
        this.date = ('0' + date.getDate()).slice(-2) + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + date.getFullYear();
        return $(function() {
          return new Ya.share({
            element: _this.$.social,
            elementStyle: {
              type: 'none',
              quickServices: ['facebook', 'twitter']
            }
          });
        });
      }
    });
  })(cs.Language);

}).call(this);
