// Generated by CoffeeScript 1.4.0

/**
 * @package   Cherrytea common
 * @category  plugins
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2015, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
*/


(function() {

  Polymer({
    ready: function() {
      return new Ya.share({
        element: this.shadowRoot.querySelector('div'),
        elementStyle: {
          type: 'none',
          quickServices: ['facebook', 'twitter']
        }
      });
    }
  });

}).call(this);
